-- FULL SCHEMA
CREATE DATABASE IF NOT EXISTS alx_book_store;
USE alx_book_store;

-- AUTHORS
CREATE TABLE IF NOT EXISTS Authors (
  author_id INT PRIMARY KEY,
  author_name VARCHAR(215) NOT NULL
) ENGINE=INNODB;

-- BOOKS
CREATE TABLE IF NOT EXISTS Books (
  book_id INT PRIMARY KEY,
  title VARCHAR(130) NOT NULL,
  author_id INT NOT NULL,
  price DOUBLE NOT NULL,
  publication_date DATE,
  CONSTRAINT FK_BOOKS_AUTHORS
    FOREIGN KEY (author_id) REFERENCES Authors(author_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB;

-- CUSTOMERS
CREATE TABLE IF NOT EXISTS Customers (
  customer_id INT PRIMARY KEY,
  customer_name VARCHAR(215) NOT NULL,
  email VARCHAR(215) NOT NULL,
  address TEXT
) ENGINE=INNODB;

-- ORDERS
CREATE TABLE IF NOT EXISTS Orders (
  order_id INT PRIMARY KEY,
  customer_id INT NOT NULL,
  order_date DATE NOT NULL,
  CONSTRAINT FK_ORDERS_CUSTOMERS
    FOREIGN KEY (customer_id) REFERENCES Customers(customer_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB;

-- ORDER_DETAILS
CREATE TABLE IF NOT EXISTS Order_Details (
  orderdetailid INT PRIMARY KEY,
  order_id INT NOT NULL,
  book_id INT NOT NULL,
  quantity DOUBLE NOT NULL,
  CONSTRAINT FK_OD_ORDERS
    FOREIGN KEY (order_id) REFERENCES Orders(order_id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT FK_OD_BOOKS
    FOREIGN KEY (book_id) REFERENCES Books(book_id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB;
